name: testing_webhook_with_s3

on: 
 push:
  branches:
   - master

jobs:
  sync_repository:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@master
      - run: aws s3 sync . s3://test-github-actions-594334056597
    env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        # SOURCE_DIR: 'public' 
