name: testing_webhook_with_s3

on: 
 push:
  branches:
   - master
  paths:
   - 'test-github-actions-594334056597/**'

jobs:
  sync_repository:
    runs-on: [self-hosted, X64, Windows, learning ]

    env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        S3_DIRECTORY: ${{ secrets.S3_DIRECTORY }}
        AWS_S3_BUCKET_CHECK: s3://test-github-actions-594334056597
        S3_DIRECTORY_CHECK: test-github-actions-594334056597/
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        # SOURCE_DIR: 'public' 

    steps:

      # In order to access folders from github repository, you need to specify this line.
      - name: Sync Master to S3
        uses: actions/checkout@v3
      - run: aws s3 sync ${{env.S3_DIRECTORY}} ${{env.AWS_S3_BUCKET}}
      # - with:
      #     token: $${{secrets.PAT}}
      # - run: aws s3 sync test-github-actions-594334056597/ s3://test-github-actions-594334056597

      - name: Merge to secondary
        uses: actions/checkout@v3
        with: 
          ref: secondary

      - run: git merge origin/master
      - run: git commit -m "Merging from master"
      - run: git push
      # - run: echo “Overwriting the existing text in the file” > test-github-actions-594334056597/testfile.txt
      # - run: make git m="Checking_automatic"
